#!/bin/sh

echo $(pwd) is the directory in which this script is being run

echo $USER_PWD is the directory in which the makeself.run script is being run

mkdir -p /tmp/sample-server

cp -R . /tmp/sample-server

cd /tmp/sample-server

rm -rf node_modules

npm install

