#!/bin/bash

# This bash script uses the current working directory to create a simple
# script to run the context-langserver command anywhere in a user's
# workspace.

cmdScript=$(pwd)/.venv/bin/context-langserver

cat << CMD_SCRIPT > $HOME/.local/bin/context-langserver
#!/bin/sh

# This shell script was created by the ConTeXt2ninja tool
#       './scripts/installEditableConTeXt-LangServerCommand'
# script.

exec $cmdScript \$@
CMD_SCRIPT

chmod a+x $HOME/.local/bin/context-langserver

echo ""
echo "Editable context-langserver command has been created"
echo ""
