#!/bin/bash

# Push changes to conTeXt-langServer to the lpic-langServer
cd ..

py_copy_langServer () {
  toDir=$1
  echo "----------------------------------------------------------"
  echo ""
  echo "Python copying conTeXt-langServer to $toDir"
  pushd $toDir
  pwd
  .venv/bin/python scripts/updateLocalContextLangServer
  popd
}

py_copy_langServer lpic-langServer
